<a href="https://colab.research.google.com/github/larabrry/deep-learning-challenge/blob/main/AlphabetSoupCharity.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [2]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df.drop(['EIN', 'NAME'], axis=1, inplace=True)
application_df

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1
...,...,...,...,...,...,...,...,...,...,...
34294,T4,Independent,C1000,ProductDev,Association,1,0,N,5000,0
34295,T4,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
34296,T3,CompanySponsored,C2000,Preservation,Association,1,0,N,5000,0
34297,T5,Independent,C3000,ProductDev,Association,1,0,N,5000,1
34298,T3,Independent,C1000,Preservation,Co-operative,1,1M-5M,N,36500179,0

In [3]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [4]:
# Look at APPLICATION_TYPE value counts for binning
app_type_count = application_df['APPLICATION_TYPE'].value_counts()
app_type_count

T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: APPLICATION_TYPE, dtype: int64

In [5]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = list(app_type_count[app_type_count<26000].index)

# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure binning was successful
application_df['APPLICATION_TYPE'].value_counts()

T3       27037
Other     7262
Name: APPLICATION_TYPE, dtype: int64

In [6]:
# Look at CLASSIFICATION value counts for binning
class_count = application_df['CLASSIFICATION'].value_counts()
class_count

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
         ...
C4120        1
C8210        1
C2561        1
C4500        1
C2150        1
Name: CLASSIFICATION, Length: 71, dtype: int64

In [7]:
# You may find it helpful to look at CLASSIFICATION value counts >1
class_more_than_one= class_count.loc[class_count >1]
class_more_than_one

C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: CLASSIFICATION, dtype: int64

In [8]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace=list(class_count[class_count < 16000].index)

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure binning was successful
application_df['CLASSIFICATION'].value_counts()

C1000    17326
Other    16973
Name: CLASSIFICATION, dtype: int64

In [9]:
# Convert categorical data to numeric with `pd.get_dummies`
application_dummies= pd.get_dummies(application_df)

In [10]:
# Split our preprocessed data into our features and target arrays
X = application_dummies.drop(['IS_SUCCESSFUL'], axis=1)
y = application_dummies['IS_SUCCESSFUL']


# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=58)

In [11]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

X_train.shape

(25724, 32)

Compile, Train and Evaluate the Model

In [12]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
number_input_features = len(X_train_scaled[0])
hidden_nodes_layer1 = 20
hidden_nodes_layer2 = 10
print(number_input_features)

nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=hidden_nodes_layer1,
             input_dim=number_input_features, activation="relu"))



# Second hidden layer
nn.add(tf.keras.layers.Dense(
    units=hidden_nodes_layer2, activation="relu"))


# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn.summary()

32
Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 20)                660

 dense_1 (Dense)             (None, 10)                210

 dense_2 (Dense)             (None, 1)                 11

=================================================================
Total params: 881 (3.44 KB)
Trainable params: 881 (3.44 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

In [14]:
# Train the model
fit_nn = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 2ms/step - loss: 0.6263 - accuracy: 0.6804
Epoch 2/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5956 - accuracy: 0.6994
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5926 - accuracy: 0.7015
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5916 - accuracy: 0.7039
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5909 - accuracy: 0.7050
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5902 - accuracy: 0.7056
Epoch 7/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5897 - accuracy: 0.7065
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5894 - accuracy: 0.7062
Epoch 9/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5895 - accuracy: 0.7058
Epoch 10/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5888 - accuracy: 0.7069
Epoch 11/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5888 - accuracy: 0.7049
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5886 - accuracy: 0.7061
Epoch 13/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5882 - accuracy: 0.7064
Epoch 14/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5884 - accuracy: 0.7077
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5880 - accuracy: 0.7078
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5875 - accuracy: 0.7075
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5876 - accuracy: 0.7075
Epoch 18/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5878 - accuracy: 0.7071
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5875 - accuracy: 0.7079
Epoch 20/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5871 - accuracy: 0.7084
Epoch 21/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5874 - accuracy: 0.7085
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5871 - accuracy: 0.7075
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5874 - accuracy: 0.7072
Epoch 24/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5870 - accuracy: 0.7081
Epoch 25/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5869 - accuracy: 0.7087
Epoch 26/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5873 - accuracy: 0.7084
Epoch 27/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5868 - accuracy: 0.7081
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5867 - accuracy: 0.7084
Epoch 29/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5869 - accuracy: 0.7087
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5869 - accuracy: 0.7075
Epoch 31/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5865 - accuracy: 0.7084
Epoch 32/50
804/804 [==============================] - 3s 3ms/step - loss: 0.5866 - accuracy: 0.7079
Epoch 33/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5861 - accuracy: 0.7077
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5863 - accuracy: 0.7084
Epoch 35/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5865 - accuracy: 0.7084
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5859 - accuracy: 0.7089
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5864 - accuracy: 0.7089
Epoch 38/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5864 - accuracy: 0.7081
Epoch 39/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5863 - accuracy: 0.7085
Epoch 40/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5862 - accuracy: 0.7095
Epoch 41/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5860 - accuracy: 0.7083
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5860 - accuracy: 0.7077
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5860 - accuracy: 0.7090
Epoch 44/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5861 - accuracy: 0.7094
Epoch 45/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5859 - accuracy: 0.7088
Epoch 46/50
804/804 [==============================] - 2s 3ms/step - loss: 0.5858 - accuracy: 0.7085
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5856 - accuracy: 0.7087
Epoch 48/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5861 - accuracy: 0.7086
Epoch 49/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5857 - accuracy: 0.7094
Epoch 50/50
804/804 [==============================] - 2s 2ms/step - loss: 0.5857 - accuracy: 0.7092

In [15]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - loss: 0.5976 - accuracy: 0.7061 - 521ms/epoch - 2ms/step
Loss: 0.5976494550704956, Accuracy: 0.7061224579811096

In [17]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [18]:
# Export our model to HDF5 file
model_path = '/content/drive/My Drive/Colab Notebooks/AlphabetSoupCharity.h5'
nn.save(model_path)